name: CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: linux-latest
    container: ubuntu:latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: mkdir new_dir

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          sudo apt update
          sudo apt install openjdk-11-jdk
