name: Docker Setup
on:
  workflow_dispatch: 
jobs:
  ci:
    runs-on: windows-latest
    steps:
    - uses: docker-practice/actions-setup-docker@master
      timeout-minutes: 12
    - run: |
        set -x

        docker version

        docker run --rm hello-world
